version: '3.9'
services:
  app:
    build:
      context: .
    ports:
      - "8000:80"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 2171122
      MYSQL_DATABASE: laravel_mysql
      MYSQL_USER: Christopher
      MYSQL_PASSWORD: 2171122